package com.moriatsushi.koject.processor.code

import com.moriatsushi.koject.processor.code.AnnotationSpecFactory.createOptInExperimental
import com.squareup.kotlinpoet.FileSpec

/**
 * Apply common settings for [FileSpec]
 */
internal fun FileSpec.Builder.applyCommon(): FileSpec.Builder {
    return apply {
        addAnnotation(createOptInExperimental())
        addFileComment("Generated by Koject. Do not modify!")
        indent("    ")
    }
}
