package com.moriatsushi.koject.processor.code

import com.squareup.kotlinpoet.FileSpec

/**
 * Apply common settings for [FileSpec]
 */
internal fun FileSpec.Builder.applyCommon(): FileSpec.Builder {
    return apply {
        addFileComment("Generated by Koject.")
        indent("    ")
    }
}
