package com.moriatsushi.koject.processor

import com.moriatsushi.koject.processor.assert.assertCompileSucceed
import com.moriatsushi.koject.processor.assert.assertFileExists
import com.moriatsushi.koject.processor.assert.assertFileTextEquals
import com.moriatsushi.koject.processor.compiletesting.KotlinCompilationFactory
import com.tschuchort.compiletesting.SourceFile
import org.intellij.lang.annotations.Language
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

class DIProcessorTest {
    @get:Rule
    val tempFolder: TemporaryFolder = TemporaryFolder()

    private val compilationFactory = KotlinCompilationFactory()

    @Test
    fun compile() {
        val folder = tempFolder.newFolder()
        val complication = compilationFactory.create(folder)
        complication.sources = listOf(inputCode)
        val result = complication.compile()

        assertCompileSucceed(result)

        val expectedClass1FactoryFile = folder.resolve(expectedClass1FactoryFilePath)
        assertFileExists(expectedClass1FactoryFile)
        assertFileTextEquals(expectedClass1FactoryText, expectedClass1FactoryFile)

        val expectedClass2FactoryFile = folder.resolve(expectedClass2FactoryFilePath)
        assertFileExists(expectedClass2FactoryFile)
        assertFileTextEquals(expectedClass2FactoryText, expectedClass2FactoryFile)

        val expectedClass3FactoryFile = folder.resolve(expectedClass3FactoryFilePath)
        assertFileExists(expectedClass3FactoryFile)
        assertFileTextEquals(expectedClass3FactoryText, expectedClass3FactoryFile)

        val expectedContainerFile = folder.resolve(expectedContainerFilePath)
        assertFileExists(expectedContainerFile)
        assertFileTextEquals(expectedContainerText, expectedContainerFile)

        val expectedStartFile = folder.resolve(expectedStartFilePath)
        assertFileExists(expectedStartFile)
        assertFileTextEquals(expectedStartText, expectedStartFile)
    }

    private val inputCode = SourceFile.kotlin(
        "Test.kt",
        """
                package com.testpackage

                import com.moriatsushi.koject.Provides

                @Provides
                class SampleClass1

                @Provides
                class SampleClass2(
                    private val sampleClass1: SampleClass1
                )

                @Provides
                class SampleClass3(
                    private val sampleClass1: SampleClass1,
                    private val sampleClass2: SampleClass2
                )
            """,
    )

    private val expectedClass1FactoryFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/generated/factory/" +
            "_com_testpackage_SampleClass1_Factory.kt"

    private val expectedClass2FactoryFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/generated/factory/" +
            "_com_testpackage_SampleClass2_Factory.kt"

    private val expectedClass3FactoryFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/generated/factory/" +
            "_com_testpackage_SampleClass3_Factory.kt"

    private val expectedContainerFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/generated/" +
            "_AppContainer.kt"

    private val expectedStartFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/_Start.kt"

    @Language("kotlin")
    private val expectedClass1FactoryText = """
        |// Generated by Koject. Do not modify!
        |package com.moriatsushi.koject.generated.factory
        |
        |import com.moriatsushi.koject.`internal`.InternalKojectApi
        |import com.moriatsushi.koject.`internal`.identifier.Identifier
        |import com.moriatsushi.koject.`internal`.identifier.StringIdentifier
        |import com.testpackage.SampleClass1
        |import kotlin.Any
        |
        |@InternalKojectApi
        |@StringIdentifier("com.testpackage.SampleClass1")
        |public class _com_testpackage_SampleClass1_Factory() {
        |    public fun create(): Any = SampleClass1()
        |
        |    public companion object {
        |        public val identifier: Identifier = Identifier.of<SampleClass1>()
        |    }
        |}
        |
    """.trimMargin()

    @Language("kotlin")
    private val expectedClass2FactoryText = """
        |// Generated by Koject. Do not modify!
        |package com.moriatsushi.koject.generated.factory
        |
        |import com.moriatsushi.koject.`internal`.InternalKojectApi
        |import com.moriatsushi.koject.`internal`.identifier.Identifier
        |import com.moriatsushi.koject.`internal`.identifier.StringIdentifier
        |import com.testpackage.SampleClass1
        |import com.testpackage.SampleClass2
        |import kotlin.Any
        |
        |@InternalKojectApi
        |@StringIdentifier("com.testpackage.SampleClass2")
        |public class _com_testpackage_SampleClass2_Factory(
        |    @StringIdentifier("com.testpackage.SampleClass1")
        |    private val provide_com_testpackage_SampleClass1: () -> Any,
        |) {
        |    public fun create(): Any = SampleClass2(
        |        provide_com_testpackage_SampleClass1() as SampleClass1,
        |    )
        |
        |    public companion object {
        |        public val identifier: Identifier = Identifier.of<SampleClass2>()
        |    }
        |}
        |
    """.trimMargin()

    @Language("kotlin")
    private val expectedClass3FactoryText = """
        |// Generated by Koject. Do not modify!
        |package com.moriatsushi.koject.generated.factory
        |
        |import com.moriatsushi.koject.`internal`.InternalKojectApi
        |import com.moriatsushi.koject.`internal`.identifier.Identifier
        |import com.moriatsushi.koject.`internal`.identifier.StringIdentifier
        |import com.testpackage.SampleClass1
        |import com.testpackage.SampleClass2
        |import com.testpackage.SampleClass3
        |import kotlin.Any
        |
        |@InternalKojectApi
        |@StringIdentifier("com.testpackage.SampleClass3")
        |public class _com_testpackage_SampleClass3_Factory(
        |    @StringIdentifier("com.testpackage.SampleClass1")
        |    private val provide_com_testpackage_SampleClass1: () -> Any,
        |    @StringIdentifier("com.testpackage.SampleClass2")
        |    private val provide_com_testpackage_SampleClass2: () -> Any,
        |) {
        |    public fun create(): Any = SampleClass3(
        |        provide_com_testpackage_SampleClass1() as SampleClass1,
        |        provide_com_testpackage_SampleClass2() as SampleClass2,
        |    )
        |
        |    public companion object {
        |        public val identifier: Identifier = Identifier.of<SampleClass3>()
        |    }
        |}
        |
    """.trimMargin()

    @Language("kotlin")
    private val expectedContainerText = """
        |// Generated by Koject. Do not modify!
        |package com.moriatsushi.koject.generated
        |
        |import com.moriatsushi.koject.`internal`.Container
        |import com.moriatsushi.koject.`internal`.InternalKojectApi
        |import com.moriatsushi.koject.`internal`.identifier.Identifier
        |import com.moriatsushi.koject.generated.factory._com_testpackage_SampleClass1_Factory
        |import com.moriatsushi.koject.generated.factory._com_testpackage_SampleClass2_Factory
        |import com.moriatsushi.koject.generated.factory._com_testpackage_SampleClass3_Factory
        |import kotlin.Any
        |
        |@InternalKojectApi
        |public class _AppContainer : Container {
        |    private val provide_com_testpackage_SampleClass1: () -> Any by lazy {
        |                _com_testpackage_SampleClass1_Factory()::create
        |            }
        |
        |    private val provide_com_testpackage_SampleClass2: () -> Any by lazy {
        |                _com_testpackage_SampleClass2_Factory(
        |                    provide_com_testpackage_SampleClass1,
        |                )::create
        |            }
        |
        |    private val provide_com_testpackage_SampleClass3: () -> Any by lazy {
        |                _com_testpackage_SampleClass3_Factory(
        |                    provide_com_testpackage_SampleClass1,
        |                    provide_com_testpackage_SampleClass2,
        |                )::create
        |            }
        |
        |    public override fun resolve(id: Identifier): Any? = when (id) {
        |        _com_testpackage_SampleClass1_Factory.identifier -> provide_com_testpackage_SampleClass1()
        |        _com_testpackage_SampleClass2_Factory.identifier -> provide_com_testpackage_SampleClass2()
        |        _com_testpackage_SampleClass3_Factory.identifier -> provide_com_testpackage_SampleClass3()
        |        else -> null
        |    }
        |}
        |
    """.trimMargin()

    @Language("kotlin")
    private val expectedStartText = """
        |// Generated by Koject. Do not modify!
        |package com.moriatsushi.koject
        |
        |import com.moriatsushi.koject.`internal`.InternalKojectApi
        |import com.moriatsushi.koject.generated._AppContainer
        |import kotlin.OptIn
        |import kotlin.Unit
        |
        |@OptIn(InternalKojectApi::class)
        |public fun Koject.start(): Unit {
        |    Koject._start(_AppContainer())
        |}
        |
    """.trimMargin()
}
