package com.moriatsushi.koject.processor

import com.moriatsushi.koject.processor.assert.assertCompileSucceed
import com.moriatsushi.koject.processor.assert.assertFileExists
import com.moriatsushi.koject.processor.compiletesting.KotlinCompilationFactory
import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import java.io.File
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

class LiProcessorCopyFactoryTest {
    @get:Rule
    val tempFolder: TemporaryFolder = TemporaryFolder()

    @Test
    fun success_copyFactory() {
        val folder = tempFolder.newFolder()
        val complication = createComplication(folder, "lib")
        complication.sources = listOf(generatedFactoryCode)
        val result = complication.compile()

        assertCompileSucceed(result)

        val expectedCopiedFactoryFile = folder.resolve(expectedCopiedFactoryFilePath)
        assertFileExists(expectedCopiedFactoryFile)
    }

    @Test
    fun success_copyCopiedFactory() {
        val folder = tempFolder.newFolder()
        val complication = createComplication(folder, "lib2")
        complication.sources = listOf(copiedCode)
        val result = complication.compile()

        assertCompileSucceed(result)

        val expectedCopiedFactoryFile = folder.resolve(expectedCopied2FactoryFilePath)
        assertFileExists(expectedCopiedFactoryFile)
    }

    @Test
    fun success_multipleCopiedFactory() {
        val folder = tempFolder.newFolder()
        val complication = createComplication(folder, "lib3")
        complication.sources = listOf(generatedFactoryCode, copiedCode)
        val result = complication.compile()

        assertCompileSucceed(result)

        val expectedCopiedFactoryFile = folder.resolve(expectedCopied3FactoryFilePath)
        assertFileExists(expectedCopiedFactoryFile)
    }

    private fun createComplication(file: File, moduleName: String): KotlinCompilation {
        val provider = TestLibProcessorProvider(
            options = DIProcessorOptions(moduleName = moduleName),
        )
        val compilationFactory = KotlinCompilationFactory(listOf(provider))
        return compilationFactory.create(file)
    }

    private val generatedFactoryCode = SourceFile.kotlin(
        "_com_lib_SampleClass_Factory.kt",
        """
                // Generated by Koject. Do not modify!
                package com.moriatsushi.koject.generated.factory
                
                import com.moriatsushi.koject.`internal`.Identifier
                import com.moriatsushi.koject.`internal`.InternalKojectApi
                import com.moriatsushi.koject.internal.Location
                import com.moriatsushi.koject.`internal`.StringIdentifier
                import kotlin.Any
                
                @InternalKojectApi
                @StringIdentifier("com.lib.SampleClass")
                @Location("/sources/Test.kt:8")
                public class _com_lib_SampleClass_Factory() {
                    public fun create(): Any = TODO()

                    public companion object {
                        public val identifier: Identifier = TODO()
                    }
                }
            """,
    )

    private val copiedCode = SourceFile.kotlin(
        "_lib__com_lib_SampleClass_Factory.kt",
        """
                // Generated by Koject. Do not modify!
                package com.moriatsushi.koject.generated.factory
                
                import com.moriatsushi.koject.`internal`.Copied
                import com.moriatsushi.koject.`internal`.Identifier
                import com.moriatsushi.koject.`internal`.InternalKojectApi
                import com.moriatsushi.koject.internal.Location
                import com.moriatsushi.koject.`internal`.StringIdentifier
                import kotlin.Any
                
                @InternalKojectApi
                @StringIdentifier("com.lib.SampleClass")
                @Location("/sources/Test.kt:8")
                @Copied(1)
                public class _lib__com_lib_SampleClass_Factory() {
                    public fun create(): Any = TODO()

                    public companion object {
                        public val identifier: Identifier = TODO()
                    }
                }
            """,
    )

    private val expectedCopiedFactoryFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/generated/factory/" +
            "_lib__com_lib_SampleClass_Factory.kt"

    private val expectedCopied2FactoryFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/generated/factory/" +
            "_lib2__lib__com_lib_SampleClass_Factory.kt"

    private val expectedCopied3FactoryFilePath =
        "ksp/sources/kotlin/com/moriatsushi/koject/generated/factory/" +
            "_lib3__com_lib_SampleClass_Factory.kt"
}
